---
dist: bionic
language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'
  # - 'nightly'

# matrix:
#   allow_failures:
#     - python: 'nightly'

before_install: pip install -U pip coveralls
install: pip install .[test]
script: pytest --cov sqla_wrapper --cov tests .
after_success: coveralls
